version: "3.7"

services:
  redis:
    image: redis:latest
    ports:
      - 56379:6379
    volumes:
      - redis-data:/data

  console:
    build:
      context: ./console
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: development
    ports:
      - 59292:9292
    command: rackup console/config.ru --host 0.0.0.0
    volumes:
      - ./console:/console
    depends_on:
      - redis

volumes:
  redis-data:
