version: "3.7"

services:
  redis:
    image: redis:latest
    ports:
      - 56379:6379
    volumes:
      - redis-data:/data

  console:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 59292:9292
    command: rackup console/config.ru --host 0.0.0.0
    volumes:
      - ./console:/console
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: sidekiq -r ./worker/worker.rb -C ./worker/sidekiq.yml
    volumes:
      - ./worker:/worker
    depends_on:
      - redis

  irb:
    build:
      context: .
      dockerfile: Dockerfile
    command: irb
    volumes:
      - ./worker:/worker
      - ./worker/.irbrc:/.irbrc

volumes:
  redis-data:
